2 user intefaces
CSC207-2022F-UofT/course-project-hello-woooorld-119 pull request #12
Opened 2022-11-14 21:25 UTC by ec105

Combing user intefaces to main branch
completed structuing : 
UIinsidechatroom
UIinsidechatroom_backend
UIoutsidechatroom
UIoutsidechatroom_backend
Loginpage
Loginusecase
user

2022-11-14 21:35 UTC, SamandarVijay approved these changes

2022-11-14 21:43 UTC, is1006 commented on src/main/java/tutorial/User.java
> -    public User(String displayName, int id) {
copy of next line, needs to be deleted

2022-11-14 21:44 UTC, is1006 requested changes

2022-11-14 21:44 UTC, is1006 commented on src/main/java/tutorial/User.java
> -        this.id = id; //need to determine how we will be creating id and ensuring it does not already exist //
can remove this line and the line below, we will be getting rid of id as a variable entirely

2022-11-14 22:12 UTC, is1006 approved these changes

2022-11-14 22:14 UTC, SamandarVijay submitted a review, later dismissed

2022-11-14 22:14 UTC, hu-jeff reviewed
Why are we gathering the username and password from the command line?

2022-11-14 22:16 UTC, ec105 commented
> Why are we gathering the username and password from the command line?

it is needed for loginsystem, when we init the user object, we assumed it is created when username and password and them both should be saved

2022-11-14 22:17 UTC, hu-jeff commented
> > Why are we gathering the username and password from the command line?
> 
> it is needed for loginsystem, when we init the user object, we assumed it is created when username and password and them both should be saved

But why are we getting this information from the command line? We should be getting it from the UI. I think we need parameters that call that function that are the username and password.

2022-11-14 22:18 UTC, ec105 commented
> > > Why are we gathering the username and password from the command line?
> > 
> > 
> > it is needed for loginsystem, when we init the user object, we assumed it is created when username and password and them both should be saved
> 
> But why are we getting this information from the command line? We should be getting it from the UI. I think we need parameters that call that function that are the username and password.

the info is received from the UI, but just need to be stored in User class when initializing

2022-11-14 22:19 UTC, hu-jeff commented
> > > > Why are we gathering the username and password from the command line?
> > > 
> > > 
> > > it is needed for loginsystem, when we init the user object, we assumed it is created when username and password and them both should be saved
> > 
> > 
> > But why are we getting this information from the command line? We should be getting it from the UI. I think we need parameters that call that function that are the username and password.
> 
> the info is received from the UI, but just need to be stored in User class when initializing

The beginlogin function loops infinitely until there is a response in the console.

2022-11-16 21:17 UTC, SamandarVijay submitted a review, later dismissed

2022-11-18 17:12 UTC, is1006 submitted a review, later dismissed

2022-11-18 22:27 UTC, hu-jeff requested changes
we shouldn't read from system.in

2022-11-19 21:30 UTC, hu-jeff requested changes
Sam's portion should be to submit the login.

In the LoginPage, line 31. Why are we using a loop for the login system? It seems no matter what the loop only runs once. Furthermore, to check if a login is valid, we should be using the accounts storage interface to check the username and password. The input for the username and password should be from the user as well. I think the checking of usernames and password should be a method that the user interface calls.

Furthermore, InputMismatchException appears to only be thrown by a Scanner. In this case, I can't see where the Scanner is being used.

In the LoginPage method, secondChoice, we should not be using system.out or system.in. 

In the file LoginUseCase, I don't think we need an array list of all users. Our Storage methods don't have any method which can give all users. Instead, what we should do is use the account storage interface to check if a username and password are valid and then we can get the user data from the user storage interface. We should similarly do the same for creating a new user.

2022-11-21 22:56 UTC, SamandarVijay commented
> Sam's portion should be to submit the login.
> 
> In the LoginPage, line 31. Why are we using a loop for the login system? It seems no matter what the loop only runs once. Furthermore, to check if a login is valid, we should be using the accounts storage interface to check the username and password. The input for the username and password should be from the user as well. I think the checking of usernames and password should be a method that the user interface calls.
> 
> Furthermore, InputMismatchException appears to only be thrown by a Scanner. In this case, I can't see where the Scanner is being used.
> 
> In the LoginPage method, secondChoice, we should not be using system.out or system.in.
> 
> In the file LoginUseCase, I don't think we need an array list of all users. Our Storage methods don't have any method which can give all users. Instead, what we should do is use the account storage interface to check if a username and password are valid and then we can get the user data from the user storage interface. We should similarly do the same for creating a new user.

I did it!

2022-11-22 03:12 UTC, closed without merging